export const ActionTypes = {
    FETCH_POSTAL_DATA: 'FETCH_POSTAL_DATA',
    FETCH_REQUEST_STARTED: 'FETCH_REQUEST_STARTED',
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_ERROR: 'FETCH_ERROR',
    REVERT_STATUS: 'REVERT_STATUS',
    SET_ERROR: 'SET_ERROR',
}